# Generated by Django 3.2 on 2023-04-14 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Выберите оценку от 1 до 10'), django.core.validators.MaxValueValidator(10, 'Выберите оценку от 1 до 10')], verbose_name='Оценка произведения')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=None, null=True, verbose_name='Рейтинг (средняя оценка)')),
            ],
        ),
    ]
