# Generated by Django 3.2 on 2023-05-01 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.category'),
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(max_length=256, null=True),
        ),
    ]
