# Generated by Django 3.2 on 2023-05-03 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230503_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='genre',
        ),
    ]
